IntArray.o:  IntArray.cpp IntArray.h
	g++ -g -Wall -c IntArray.cpp
IntArrayDriver.o:  IntArrayDriver.cpp IntArray.h
	g++ -g -Wall -c IntArrayDriver.cpp
IntArrayDriver:  IntArray.o IntArrayDriver.o
	g++ -g -Wall -o IntArrayDriver IntArray.o IntArrayDriver.o
